project_id = "ijagpzrtjljtfaefvgej"

[functions.get-account-balance]
verify_jwt = true

[functions.get-market-prices]
verify_jwt = false

[functions.place-order]
verify_jwt = true

[functions.get-open-orders]
verify_jwt = true

[functions.test-binance-connection]
verify_jwt = false

[functions.get-public-ip]
verify_jwt = false