// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijagpzrtjljtfaefvgej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYWdwenJ0amxqdGZhZWZ2Z2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzQ1OTYsImV4cCI6MjA2OTExMDU5Nn0.ZKX9gjtTQvZns-WhSOoJAjm5D4cB6fZdv1ka_PXFemU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});